IMPLENTED CI/CD

diff --git a/config/ci/build b/config/ci/build
--- a/config/ci/build
+++ b/config/ci/build
@@ -1,8 +1,25 @@
 #!/bin/bash
-
-
+set -e
 echoinfo ${CI_COMMIT_MESSAGE} | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' && [ "${CI_COMMIT_REF_NAME}" = "master" ] && echo "Skipping version builds on the master branche to avoid the pipeline doing the same work twice" && exit;
+TARGET=${1}
+if [ -z "${TARGET}" ]; then
+  echo "Argument TARGET missing"
+  exit 1
+fi
+
 source ./config/ci/.env
+if [ "${TARGET}" = "etl"]; then
+  DOCKER_IMAGE_NAME+="-etl"
+  DOCKER_FILE=./config/docker/Dockerfile
+elif [ "${TARGET}" = "crawler"]; then
+  DOCKER_IMAGE_NAME+="-crawler"
+  DOCKER_FILE="./crawler/Dockerfile"
+else
+  echo "Argument ${TARGET} not recognized"
+  exit 1
+fi
+
+
 if [ -n "${FORCE}" ]; then
   DOCKER_ARG="--no-cache"
 fi
@@ -10,7 +27,7 @@ fi
 now=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
 echoinfo "Building for tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} at ${now}"
 docker build \
-    -f ./config/docker/Dockerfile \
+    -f ${DOCKER_FILE} \
     ${DOCKER_ARG} \
     --build-arg "NPM_TOKEN=${NPM_TOKEN}" \
     --build-arg "BUILD_REF=${CI_COMMIT_REF_NAME}" \
diff --git a/config/ci/run b/config/ci/run
--- a/config/ci/run
+++ b/config/ci/run
@@ -2,17 +2,40 @@
 set -e
 source ./config/ci/.env
 MODE=${1}
+if [ -z "${DESTINATION_DATASET}" ]; then
+  echo "Environment variable DESTINATION_DATASET missing"
+  exit 1;
+fi
 if [ "${MODE}" = "acceptance" ] || [ "${MODE}" = "production" ]; then
   CONTAINER_NAME="ci-edm-conversie-project-${MODE}"
   #remove other runs when needed. Otherwise, we'd have duplicate runs working on the same directory
   docker rm -f ${CONTAINER_NAME} 2> /dev/null || true
+  echo "Running ETL"
   docker run --rm \
     -v /scratch/edm-conversie-project-${MODE}:/home/triply/data \
     -e TRIPLYDB_TOKEN=${TRIPLYDB_TOKEN} \
     -e TRIPLYDB_ACCOUNT=${TRIPLYDB_ACCOUNT} \
     -e MODE=${MODE} \
     --name ${CONTAINER_NAME} \
-    ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
+    ${DOCKER_IMAGE_NAME}-etl:${DOCKER_IMAGE_TAG}
+  echo "Running crawler"
+  docker run --rm \
+    -v /scratch/edm-conversie-project-${MODE}/rdf:/data \
+    -e TRIPLYDB_TOKEN=${TRIPLYDB_TOKEN} \
+    -e TRIPLYDB_ACCOUNT=${TRIPLYDB_ACCOUNT} \
+    -e MODE=${MODE} \
+    --name ${CONTAINER_NAME} \
+    ${DOCKER_IMAGE_NAME}-crawler:${DOCKER_IMAGE_TAG} \
+    ./rdf2edm.sh -input_file /data/${DESTINATION_DATASET}.ttl -output_file /data/${DESTINATION_DATASET}.xml.zip
+  echo "Running ETL after hook"
+  docker run --rm \
+    -v /scratch/edm-conversie-project-${MODE}:/home/triply/data \
+    -e TRIPLYDB_TOKEN=${TRIPLYDB_TOKEN} \
+    -e TRIPLYDB_ACCOUNT=${TRIPLYDB_ACCOUNT} \
+    -e MODE=${MODE} \
+    --name ${CONTAINER_NAME} \
+    ${DOCKER_IMAGE_NAME}-etl:${DOCKER_IMAGE_TAG} \
+    yarn ratt ./lib/after.js
 else
   echoerr "Expected ${MODE} to be 'production' or 'acceptance'"
   exit 1;
